# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        pip-version: [ "22.2.1", "22.2", "22.1.2", "22.1.1", "22.1", "22.0.4", "22.0.3", "22.0.2", "22.0.1" ]
        python-version: [ "3.9" ]

    env:
      DRAINPIPE_DIRECTORY: "$GITHUB_WORKSPACE/.drain/"

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install pip==${{ matrix.pip-version }}

    - name: Test with pytest
      run: |
        mkdir -p "$env:DRAINPIPE_DIRECTORY"
        python ./drainpipe.py drain
        pip install sphinx

    - name: Confirm patch working
      run: |
        if [ $(ls | wc -l) == 0 ]; then echo 1; else echo 0; fi
      shell: bash
